- name: make schema directory
  file: path=$HOME/.vim/colors state=directory
- name: get schema
  git: repo=https://github.com/Haron-Prime/Antares.git dest=$HOME/Antares
- name: set schema Antares
  copy: remote_src=true src=$HOME/Antares/colors/antares.vim dest=$HOME/.vim/colors/antares.vim
- name: clean up
  file: path=$HOME/Antares state=absent
- name: make setting directory
  file: path=$HOME/.vim/setting state=directory
- name: link vim initial setting
  file: src="{{ role_path }}/files/init" dest=$HOME/.vim/setting/init state=link
- name: link vim initial setting
  file: src="{{ role_path }}/files/init.vim" dest=$HOME/.vim/setting/init.vim state=link
- name: remove setting
  file: path=$HOME/.vimrc state=absent
- name: make vimrc
  copy:
    content: 'runtime! setting/*.vim'
    dest: $HOME/.vimrc
