homebrew_taps:
  - homebrew/cask
  - homebrew/core
homebrew_packages:
  - name: ansible
  - name: deno
  - name: git
  - name: python3
  - name: ripgrep
  - name: tig
  - name: tree
  - name: vim
  - name: wget
  - name: zsh-completions
  - name: docker
  - name: docker-compose
  - name: colima
  - name: jq
  - name: awscli
  - name: rustup-init
  - name: nodebrew
  - name: poetry
homebrew_casks:
  - name: kitty
  - name: deepl
  - name: google-chrome
  - name: google-japanese-ime
  - name: texturepacker
