- name: update
  community.general.homebrew:
    update_homebrew: yes
- name: homebrew packages install
  community.general.homebrew:
    name: "{{ item.name }}"
    state: latest
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ homebrew_packages }}"
- name: link
  community.general.homebrew:
    name: "{{ item.name }}"
    state: linked
  with_items: "{{ homebrew_packages }}"
- name: Create askpass script for installer
  copy:
    content: |
      #!/bin/bash
      echo "{{ sudo_password }}"
    dest: /tmp/askpass.sh
    mode: '0700'
- name: homebrew casks install
  homebrew_cask:
    name: "{{ item.name }}"
    state: latest
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
    SUDO_ASKPASS: /tmp/askpass.sh
  with_items: "{{ homebrew_casks }}"
- name: Clean up askpass script
  file:
    path: /tmp/askpass.sh
    state: absent
