homebrew_packages:
  - name: ansible
  - name: deno
  - name: git
  - name: gh
  - name: pre-commit
  - name: ripgrep
  - name: tig
  - name: tree
  - name: vim
  - name: wget
  - name: zsh-completions
  - name: docker
  - name: docker-compose
  - name: colima
  - name: lima-additional-guestagents
  - name: jq
  - name: awscli
  - name: go
  - name: rustup
  - name: fnm
  - name: uv
homebrew_casks:
  - name: cmux
  - name: google-chrome
  - name: google-japanese-ime
  - name: drawio
  - name: texturepacker
  - name: visual-studio-code
  - name: claude-code@latest
  - name: codex
