- name: make vim plugin directory
  file: path=$HOME/.vim/dein/repos/github.com/Shougo/dein.vim state=directory
- name: get vim plugin controller
  git: repo=https://github.com/Shougo/dein.vim.git dest=$HOME/.vim/dein/repos/github.com/Shougo/dein.vim
- name: make vim schema directory
  file: path=$HOME/.vim/colors state=directory
- name: get vim schema
  git: repo=https://github.com/Haron-Prime/Antares.git dest=$HOME/Antares
- name: set vim schema Antares
  copy: remote_src=true src=$HOME/Antares/colors/antares.vim dest=$HOME/.vim/colors/antares.vim
- name: clean up
  file: path=$HOME/Antares state=absent
- name: link vim after
  file: src="{{ role_path }}/files/after" dest=$HOME/.vim/after state=link
- name: make vim setting directory
  file: path=$HOME/.vim/setting state=directory
- name: link vim base setting
  file: src="{{ role_path }}/files/init.vim" dest=$HOME/.vim/setting/init.vim state=link
- name: remove vim setting
  file: path=$HOME/.vimrc state=absent
- name: make vimrc
  copy:
    content: 'runtime! setting/*.vim'
    dest: $HOME/.vimrc
